#!/usr/bin/env python3
"""Helper script to e used as a pre-commit hook."""
import os
import sys
import subprocess


def gitleaksEnabled():
    """Determine if the pre-commit hook for gitleaks is enabled."""
    out = subprocess.getoutput("git config --bool hooks.gitleaks")
    if out == "false":
        return False
    return True

def gitleaksSkipped():
    """Determine if the pre-commit hook for gitleaks is skipped."""
    skip = os.getenv('SKIP')
    if skip == 'gitleaks':
        return True
    return False



if gitleaksEnabled() and not gitleaksSkipped():
    exitCode = os.WEXITSTATUS(os.system('gitleaks protect -v --staged -c ~/.mindsmiths-gitleaks.toml'))
    if exitCode == 1:
        print('''Warning: gitleaks has detected sensitive information in your changes.
To disable the gitleaks precommit hook run the following command:
    git config hooks.gitleaks false
''')
        sys.exit(1)
elif gitleaksSkipped():
    print('gitleaks precommit skipped!')
else:
    print('gitleaks precommit disabled\
     (enable with `git config hooks.gitleaks true`)')
